version: '3'
services:
  api:
    links:
      - mysql
    build:
      context: . 
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/haru0017/go-clean-architecture

  mysql:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    hostname: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./docker/db/mysql:/docker-entrypoint-initdb.d
      - ./docker/db/mysql/mysql_data:/var/lib/mysql